// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMkUuyAYuhFB_DiMjgdBSG0ZxC8mvPylY',
    appId: '1:1060836354284:web:c7dcd93d02c36fbd8b9dc9',
    messagingSenderId: '1060836354284',
    projectId: 'to-do-app-758fc',
    authDomain: 'to-do-app-758fc.firebaseapp.com',
    storageBucket: 'to-do-app-758fc.firebasestorage.app',
    measurementId: 'G-SQ90B5D764',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmIk1YDWkaY8hue_xBAQfAULJ7keG9dOQ',
    appId: '1:1060836354284:android:71c0fac6947f7b1d8b9dc9',
    messagingSenderId: '1060836354284',
    projectId: 'to-do-app-758fc',
    storageBucket: 'to-do-app-758fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0ZmKkt8bA_2wY2EmElleIWIODJ-56PA0',
    appId: '1:1060836354284:ios:72943e27a797ef698b9dc9',
    messagingSenderId: '1060836354284',
    projectId: 'to-do-app-758fc',
    storageBucket: 'to-do-app-758fc.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0ZmKkt8bA_2wY2EmElleIWIODJ-56PA0',
    appId: '1:1060836354284:ios:72943e27a797ef698b9dc9',
    messagingSenderId: '1060836354284',
    projectId: 'to-do-app-758fc',
    storageBucket: 'to-do-app-758fc.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMkUuyAYuhFB_DiMjgdBSG0ZxC8mvPylY',
    appId: '1:1060836354284:web:b150d9a0d9878c938b9dc9',
    messagingSenderId: '1060836354284',
    projectId: 'to-do-app-758fc',
    authDomain: 'to-do-app-758fc.firebaseapp.com',
    storageBucket: 'to-do-app-758fc.firebasestorage.app',
    measurementId: 'G-RRV6LTNTEZ',
  );

}